In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

people=pd.read_csv('./Data/인구수.csv')
people.columns=[i for i in range(1991, 2024)] 
people.index=[i for i in range(0,576,32)]
people.loc[:,1991].values

array(['전국', '서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종', '경기', '강원',
       '충북', '충남', '전북', '전남', '경북', '경남', '제주'], dtype=object)

In [16]:
highschool=pd.read_csv('./Data/highschool.csv')
participants=pd.read_csv('./Data/participants.csv')
ready=pd.read_csv('./Data/ready.csv')
school=pd.read_csv('./Data/school.csv')
total=pd.read_csv('./Data/total.csv')


In [17]:
for col in highschool.columns:
    print(highschool[col].unique())

['전체' '대도시' '서울' '광역시' '대도시 이외' '중소도시' '읍면지역' '과목: 일반교과 사교육' '국어' '영어'
 '수학' '사회, 과학' '논술' '제2외국어, 한문, 컴퓨터 등' '컴퓨터' '제2외국어, 한문 등'
 '과목: 예체능,취미,교양 사교육' '음악' '미술' '체육' '취미·교양' '과목: 취업관련 사교육'
 '과목: 진로·진학 학습상담' '유형: 일반교과 사교육' '개인과외' '그룹과외' '학원수강' '방문학습지'
 '유료인터넷 및 통신강좌 등' '유형: 예체능, 취미,교양 사교육' '방문수업 및 기타']
[2019 2020 2021 2022]
['전체' '1학년' '2학년' '3학년']
[61.  64.5 62.3 56.4 61.6 64.3 63.3 57.  64.6 68.  66.2 59.8 66.  69.6
 66.8 67.4 65.6 61.2 64.9 67.8 65.1 61.8 68.1 70.4 69.1 72.1 69.3 66.1
 68.9 68.2 69.5 70.1 71.6 69.8 73.4 74.5 73.2 72.6 75.  77.2 73.5 74.1
 62.9 55.7 65.  56.7 64.4 67.6 60.  68.4 66.3 60.4 58.4 62.5 60.1 53.1
 59.3 61.9 62.1 53.7 66.4 64.2 56.  63.9 67.9 65.2 58.5 59.5 57.7 65.8
 59.4 67.5 71.9 47.1 48.7 36.4 47.8 50.2 50.8 42.2 51.5 52.9 46.  53.5
 57.4 46.8 49.7 55.9 50.6 43.2 51.4 56.9 52.4 44.7 54.5 60.7 47.4 55.4
 56.5 48.6 18.9 19.8 17.1 19.6 20.3 21.2 23.9 24.8 23.7 23.3 25.8 27.8
 25.  24.6 36.3 45.  36.6 28.1 38.6 46.6 39.6 29.4 41.  42.  30.9 42.1
 51.2 42.8 

In [18]:
for col in participants.columns:
    print(participants[col].unique())

['대상분포(%)' '사교육 참여' '과목: 일반교과 사교육' '국  어' '영  어' '수  학' '사회, 과학' '논  술'
 '제2외국어, 한문, 컴퓨터 등' '컴퓨터' '제2외국어, 한문 등' '과목: 예체능,취미,교양 사교육' '음  악' '미  술'
 '체  육' '취미·교양' '과목: 취업관련 사교육' '과목: 진로·진학 학습상담' '유형: 일반교과 사교육' '개인과외'
 '그룹과외' '학원수강' '방문학습지' '유료인터넷 및 통신강좌 등' '유형: 예체능,취미,교양 사교육' '방문수업 및 기타']
[2013 2014 2015 2016 2017 2018 2019 2020 2021 2022]
['평  균 (%)' '대도시 (%)' '서  울 (%)' '광역시 (%)' '대도시이외 (%)' '중소도시 (%)'
 '읍면지역 (%)']
[100.   42.5  17.1  25.4  57.5  42.8  14.7  42.   16.9  25.   58.   42.7
  15.3  41.7  16.8  24.9  58.3  45.   13.3  41.2  16.6  24.6  58.8  46.
  12.8  40.7  16.4  24.3  59.3  43.7  15.6  40.1  16.1  23.9  59.9  44.9
  15.   39.6  15.9  23.7  60.4  15.5  39.4  15.7  23.6  60.6  44.2  39.
  23.5  61.   44.5  16.5  38.7  23.4  61.3  44.8  68.8  71.4  75.   68.9
  67.   70.2  68.6  70.5  74.4  67.8  67.2  70.1  59.2  71.   74.3  70.
  57.7  69.9  73.7  67.4  66.2  57.9  71.2  73.9  77.6  69.3  71.8  62.2
  72.8  75.3  79.9  72.3  74.2  62.   74.8  77.   80.   73.3  76.3  64.5

In [19]:
for col in ready.columns:
    print(ready[col].unique())

['대학입학 준비 여부' '학원을 다니고 있었다' '개인 및 그룹과외를 받고 있었다' 'EBS 수능특강을 시청하고 있었다'
 '인터넷을 이용한 온라인 과외를 받았다' 'EBS 외 인터넷을 이용한 온라인 학습을 받았다']
['응답자수 (명)' '예 (%)' '아니요 (%)']
['전문대(2년)' '전문대(3년)' '전문대(4년)' '대학(4년)' '대학(5년)' '대학(6년)' '기타']
[2019 2020 2018]
[1.488e+03 1.496e+03 5.920e+02 5.850e+02 1.870e+02 1.980e+02 5.107e+03
 5.348e+03 3.600e+01 4.600e+01 6.600e+01 7.200e+01 0.000e+00 3.900e+00
 3.000e+00 2.900e+00 3.500e+00 3.800e+00 2.100e+00 2.200e+00 7.000e+00
 2.600e+00 1.140e+01 5.100e+00 9.610e+01 9.700e+01 9.710e+01 9.650e+01
 9.620e+01 9.790e+01 9.780e+01 9.300e+01 9.740e+01 8.860e+01 9.490e+01
 6.200e+01 5.900e+01 4.500e+01 2.200e+01 1.700e+01 2.100e+01 6.000e+00
 4.000e+00 3.260e+02 1.940e+02 1.180e+02 1.000e+00 2.000e+00 3.160e+01
 2.990e+01 3.030e+01 3.830e+01 1.220e+01 6.380e+01 4.000e+01 1.860e+01
 5.560e+01 4.480e+01 4.200e+01 1.000e+02 6.840e+01 7.010e+01 7.800e+01
 6.970e+01 6.170e+01 8.780e+01 3.620e+01 6.000e+01 8.140e+01 4.440e+01
 5.520e+01 5.800e+01 7.600e+00 4.200e+00 2.260e+01 9.00

In [20]:
for col in school.columns:
    print(school[col].unique())

['총계' '서울특별시' '부산광역시' '대구광역시' '인천광역시' '광주광역시' '대전광역시' '울산광역시' '세종특별자치시'
 '경기도' '강원특별자치도' '충청북도' '충청남도' '전라북도' '전라남도' '경상북도' '경상남도' '제주특별자치도']
['계' '국립' '공립' '사립']
[2022]
['학교수 (개)' '학급수 (개)' '학생수 (명)' '교직원수 (명)' '교실수 (개)']
['소계' '초등학교 과정' '중학교 과정' '고등학교 과정' '여자' '교원수' '직원수' '일반교실' '교과교실' '특별교실'
 '수준별교실']
['소계' '여자']
['72' '661' '68' '269' '324' '9110' '5363' '860' '432' '6016' '3907'
 '2234' '1024' '1525' '972' '286' '139' '1415' '679' '173' '538' '25' '2'
 '21' '-' '556' '455' '56' '49' '5' '61' '23' '32' '6' '35' '296' '22'
 '52' '222' '1163' '602' '167' '90' '381' '188' '615' '834' '531' '135'
 '74' '609' '247' '44' '316' '344' '46' '196' '102' '7391' '4306' '693'
 '342' '5079' '3264' '1619' '700' '635' '392' '146' '60' '745' '409' '97'
 '216' '16' '205' '87' '112' '3028' '2343' '42' '2743' '2193' '243' '127'
 '466' '75' '41' '406' '157' '73' '168' '8' '104' '116' '53' '266' '180'
 '177' '62' '114' '1' '80' '66' '2356' '1835' '2187' '1738' '144' '95'
 '26' '14' '48' '7' '10' '54' '4

In [21]:
for col in total.columns:
    print(total[col].unique())

['전체 (억원)' '초등학교 (억원)' '중학교 (억원)' '고등학교 (억원)' '일반고 (억원)']
[2013 2014 2015 2016 2017 2018 2019 2020 2021 2022]
['전체' '대도시' '서울' '광역시' '대도시 이외' '중소도시' '읍면지역' '과목: 일반교과 사교육' '국어' '영어'
 '수학' '사회, 과학' '논술' '제2외국어, 한문, 컴퓨터 등' '과목: 예체능, 취미·교양 사교육' '음악' '미술' '체육'
 '취미·교양' '과목: 취업관련 사교육' '유형: 일반교과 사교육' '개인과외' '그룹과외' '학원수강' '방문학습지'
 '유료인터넷 및 통신강좌 등' '유형: 예체능, 취미·교양 사교육' '방문수업 및 기타' '과목: 진로·진학 학습상담' '컴퓨터'
 '제2외국어, 한문 등']
[1.8596e+05 8.9716e+04 4.3629e+04 ... 2.3170e+03 5.5540e+03 1.6200e+02]
